// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlfzj4H5ncP_AYXeTYF9cJ8Qqkp39WyIY',
    appId: '1:211624258392:web:d273005ce02828df95932d',
    messagingSenderId: '211624258392',
    projectId: 'zoom-3651e',
    authDomain: 'zoom-3651e.firebaseapp.com',
    storageBucket: 'zoom-3651e.appspot.com',
    measurementId: 'G-WFCG4DXXT3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxxIU6x_8Vg7q5pdQlIyW6rsiP_FujoEM',
    appId: '1:211624258392:android:1891fbead60f6b4095932d',
    messagingSenderId: '211624258392',
    projectId: 'zoom-3651e',
    storageBucket: 'zoom-3651e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgSizr39dk3NHOXcZrajfXuZKh5aMV-AI',
    appId: '1:211624258392:ios:03685602958038b395932d',
    messagingSenderId: '211624258392',
    projectId: 'zoom-3651e',
    storageBucket: 'zoom-3651e.appspot.com',
    iosClientId: '211624258392-va5u14iiihgu541pi6ojdllgka5d9lel.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomClone',
  );
}
